New secret mounting in workflow

diff --git a/.github/workflows/main-tests-deploy.yml b/.github/workflows/main-tests-deploy.yml
--- a/.github/workflows/main-tests-deploy.yml
+++ b/.github/workflows/main-tests-deploy.yml
@@ -44,9 +44,9 @@ jobs:
       - name: Reconstruct secret JSONs
         run: |
           mkdir -p secrets
-          echo "${{ secrets.ENGAGEPOINT_SERVICEINFO }}" > secrets/engagepoint-serviceinfo.json
-          echo "${{ secrets.ENGAGEPOINT_EMAIL_SMTPSETTINGS }}" > secrets/engagepoint-email-smtpsettings.json
-          echo "${{ secrets.ENGAGEPOINT_FIREBASE_ADMINSDK }}" > secrets/engagepoint-firebase-adminsdk.json
+          echo "${{ secrets.ENGAGEPOINT_SERVICEINFO }}" | base64 --decode > secrets/engagepoint-serviceinfo.json
+          echo "${{ secrets.ENGAGEPOINT_EMAIL_SMTPSETTINGS }}" | base64 --decode > secrets/engagepoint-email-smtpsettings.json
+          echo "${{ secrets.ENGAGEPOINT_FIREBASE_ADMINSDK }}" | base64 --decode > secrets/engagepoint-firebase-adminsdk.json
         shell: bash
 
       - name: Build Docker image
@@ -63,6 +63,7 @@ jobs:
             -e SERVICE_INFORMATION=/app/secrets/engagepoint-serviceinfo.json \
             -e EMAIL_SETTINGS=/app/secrets/engagepoint-email-smtpsettings.json \
             -e GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/engagepoint-firebase-adminsdk.json \
+            -e FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
             -v $PWD/secrets:/app/secrets \
             business-verification-service:pr-${{ github.event.pull_request.number }})
 
@@ -70,7 +71,6 @@ jobs:
 
           # Wait a while to see if it crashes
           sleep 30
-          docker exec $CONTAINER_ID head -c 5 /app/secrets/engagepoint-serviceinfo.json | hexdump -C
 
           # Check the logs for "Startup: Completed." message
           if ! docker logs $CONTAINER_ID 2>&1 | grep -q "Startup: Completed."; then
@@ -80,6 +80,12 @@ jobs:
           fi
 
           echo "Container is running."
+
+      - name: Check container logs if failure
+        if: failure()
+        run: |
+          echo "Showing container logs after failure..."
+          docker logs $CONTAINER_ID || true
 
       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v1
